
# Site settings
title: LISA Project
email: laurent.christophe@sirris.be
description: LLM Implementation, Security & Adaptation
baseurl: ""  # for project pages use "/repo-name"
url: "https://sirris-be.github.io/lisa"

# Source directory for Markdown
source: content

# Destination folder (where the static site is built)
destination: _site

# Layouts
layouts_dir: _layouts
includes_dir: _includes

# Permalinks (optional)
permalink: /:title/

# Collections (optional, if you want to group content)
collections:
  events:
    output: true
    permalink: /events/:title/

# Markdown processor
markdown: kramdown

nav:
  - title: "Home"
    url: "/"
  - title: "Events"
    url: "/events/"
  - title: "About"
    url: "/about.html"
