
title: LISA
email: laurent.christophe@sirris.be
description: Homepage of the LISA Research Project
baseurl: ""
url: "https://sirris-be.github.io/lisa"

source: content

destination: _site

timezone: Europe/Brussels

layouts_dir: _layouts
includes_dir: _includes

collections:
  events:
    output: true
